In [11]:
import torch
import numpy as np

from helper import *
from models import *


dtype = torch.float
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")


# Prepare MNIST datasets
batch_size = 512
dataset = 'cifar10' # choose 'mnist', 'cifar10' 
train_loader, test_loader, n_in, n_out = load_dataset(dataset, batch_size=batch_size)
seed = np.random.randint(100) # later set a seed to fix the initialization
# seed = 30
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
pretrained = False


# Define the network dimensions
num_steps = 8
n_first_hidden = 100
num_binary_layers = 4
n_hidden = 100
num_hidden_layers = num_binary_layers-1

list_n_first_hidden = [20*i for i in range(1,11)]
list_num_binary_layers = [i for i in range(2,8)]
list_n_hidden = [20*i for i in range(1,11)]
list_num_steps = [2,4,6,8,12,16,24,32,48,64]
list_num_hidden_layers = [i for i in range(1,7)]


# Training hyperparameters
num_epochs = 50
lr = 1e-3
weight_decay= 5e-4
lr_step = num_epochs/2
lr_gamma = 0.1


# Display hyperparameters
save_path = './example_results/'
os.makedirs(save_path, exist_ok=True)
display_iter = int((60000/batch_size) / 4) #print batch statistics 4 times per epoch
eval_epoch = int(num_epochs / 10) #evaluate and save params after every 10-th epoch
save_epoch = True









Files already downloaded and verified
Files already downloaded and verified


In [ ]:
# Display parameters
experiment_snn(train_loader, test_loader, n_in, n_out, num_steps, n_first_hidden, num_binary_layers, n_hidden, 
            save_path=save_path, pretrained=False, num_epochs=num_epochs, lr=lr, weight_decay=0, lr_step=lr_step, 
            lr_gamma=lr_gamma, output='spike', display_iter =display_iter, eval_epoch=eval_epoch, save_epoch=False)

# experiment_ann(train_loader, test_loader, n_in, n_out, n_first_hidden, num_hidden_layers, 
#             n_hidden, save_path=save_path, pretrained=False, num_epochs=num_epochs, lr=lr, weight_decay=weight_decay, 
#             lr_step=lr_step, lr_gamma=lr_gamma, display_iter =display_iter, eval_epoch=eval_epoch, save_epoch=False)


In [18]:
seed = 30
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
net = SNN(num_steps=num_steps, n_first_hidden=n_first_hidden, num_binary_layers = num_binary_layers, n_hidden = n_hidden).to(device)
for i in net.parameters():
    print(i)

Parameter containing:
tensor([[ 0.0286,  0.0176, -0.0020,  ...,  0.0195,  0.0097, -0.0287],
        [ 0.0123, -0.0279,  0.0041,  ...,  0.0310,  0.0039,  0.0100],
        [ 0.0317,  0.0018, -0.0168,  ...,  0.0319,  0.0012, -0.0267],
        ...,
        [-0.0087, -0.0076,  0.0309,  ..., -0.0356, -0.0025, -0.0301],
        [ 0.0092,  0.0049,  0.0252,  ...,  0.0193,  0.0256,  0.0211],
        [-0.0115, -0.0131, -0.0284,  ..., -0.0301, -0.0303,  0.0328]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0047,  0.0227,  0.0067, -0.0009,  0.0187, -0.0138,  0.0019, -0.0246,
         0.0030,  0.0020,  0.0180,  0.0084, -0.0024,  0.0353,  0.0106,  0.0279,
        -0.0246, -0.0345,  0.0120,  0.0017, -0.0191, -0.0267,  0.0223,  0.0216,
         0.0087, -0.0220,  0.0219, -0.0302,  0.0194,  0.0314,  0.0232, -0.0292,
         0.0008, -0.0335, -0.0210,  0.0166,  0.0219,  0.0156, -0.0153,  0.0018,
        -0.0026,  0.0175,  0.0108,  0.0241,  0.0141, -0.0232,  0.0039,  0.0170

In [19]:
seed = 30
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

net2 = SNN(num_steps=num_steps, n_first_hidden=n_first_hidden, num_binary_layers = num_binary_layers, n_hidden = n_hidden).to(device)

for i in net2.parameters():
    print(i)

Parameter containing:
tensor([[ 0.0286,  0.0176, -0.0020,  ...,  0.0195,  0.0097, -0.0287],
        [ 0.0123, -0.0279,  0.0041,  ...,  0.0310,  0.0039,  0.0100],
        [ 0.0317,  0.0018, -0.0168,  ...,  0.0319,  0.0012, -0.0267],
        ...,
        [-0.0087, -0.0076,  0.0309,  ..., -0.0356, -0.0025, -0.0301],
        [ 0.0092,  0.0049,  0.0252,  ...,  0.0193,  0.0256,  0.0211],
        [-0.0115, -0.0131, -0.0284,  ..., -0.0301, -0.0303,  0.0328]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0047,  0.0227,  0.0067, -0.0009,  0.0187, -0.0138,  0.0019, -0.0246,
         0.0030,  0.0020,  0.0180,  0.0084, -0.0024,  0.0353,  0.0106,  0.0279,
        -0.0246, -0.0345,  0.0120,  0.0017, -0.0191, -0.0267,  0.0223,  0.0216,
         0.0087, -0.0220,  0.0219, -0.0302,  0.0194,  0.0314,  0.0232, -0.0292,
         0.0008, -0.0335, -0.0210,  0.0166,  0.0219,  0.0156, -0.0153,  0.0018,
        -0.0026,  0.0175,  0.0108,  0.0241,  0.0141, -0.0232,  0.0039,  0.0170